<div>
<img src=https://www.institutedata.com/wp-content/uploads/2019/10/iod_h_tp_primary_c.svg width="300">
</div>

# Lab 4.1.2 Linear Regression

## Prediction of House Price Using Linear Regression

### Data

The Sacramento real estate transactions file is a list of 985 real estate transactions in the Sacramento area reported over a five-day period, as reported by the Sacramento Bee.

In [30]:
import pandas as pd
import numpy as np
import pandas as pd

%matplotlib inline

### 1. Explore Data

Perform EDA on this dataset. Find Dependent and Independent Variables to predict house price.

In [31]:
# Read CSV
house = pd.read_csv("C:/Users/carls/Desktop/IOD/Data/Sacramento_transactions.csv")

In [32]:
house.head()

street        city    zip state  beds  baths  sq__ft  \
0      3526 HIGH ST  SACRAMENTO  95838    CA     2      1     836   
1       51 OMAHA CT  SACRAMENTO  95823    CA     3      1    1167   
2    2796 BRANCH ST  SACRAMENTO  95815    CA     2      1     796   
3  2805 JANETTE WAY  SACRAMENTO  95815    CA     2      1     852   
4   6001 MCMAHON DR  SACRAMENTO  95824    CA     2      1     797   

          type                     sale_date  price   latitude   longitude  
0  Residential  Wed May 21 00:00:00 EDT 2008  59222  38.631913 -121.434879  
1  Residential  Wed May 21 00:00:00 EDT 2008  68212  38.478902 -121.431028  
2  Residential  Wed May 21 00:00:00 EDT 2008  68880  38.618305 -121.443839  
3  Residential  Wed May 21 00:00:00 EDT 2008  69307  38.616835 -121.439146  
4  Residential  Wed May 21 00:00:00 EDT 2008  81900  38.519470 -121.435768

In [33]:
house.tail()

street             city    zip state  beds  baths  sq__ft  \
980   9169 GARLINGTON CT       SACRAMENTO  95829    CA     4      3    2280   
981      6932 RUSKUT WAY       SACRAMENTO  95823    CA     3      2    1477   
982    7933 DAFFODIL WAY   CITRUS HEIGHTS  95610    CA     3      2    1216   
983     8304 RED FOX WAY        ELK GROVE  95758    CA     4      2    1685   
984  3882 YELLOWSTONE LN  EL DORADO HILLS  95762    CA     3      2    1362   

            type                     sale_date   price   latitude   longitude  
980  Residential  Thu May 15 00:00:00 EDT 2008  232425  38.457679 -121.359620  
981  Residential  Thu May 15 00:00:00 EDT 2008  234000  38.499893 -121.458890  
982  Residential  Thu May 15 00:00:00 EDT 2008  235000  38.708824 -121.256803  
983  Residential  Thu May 15 00:00:00 EDT 2008  235301  38.417000 -121.397424  
984  Residential  Thu May 15 00:00:00 EDT 2008  235738  38.655245 -121.075915

In [34]:
house.describe()

zip        beds       baths       sq__ft          price  \
count    985.000000  985.000000  985.000000   985.000000     985.000000   
mean   95750.697462    2.911675    1.776650  1314.916751  234144.263959   
std       85.176072    1.307932    0.895371   853.048243  138365.839085   
min    95603.000000    0.000000    0.000000     0.000000    1551.000000   
25%    95660.000000    2.000000    1.000000   952.000000  145000.000000   
50%    95762.000000    3.000000    2.000000  1304.000000  213750.000000   
75%    95828.000000    4.000000    2.000000  1718.000000  300000.000000   
max    95864.000000    8.000000    5.000000  5822.000000  884790.000000   

         latitude   longitude  
count  985.000000  985.000000  
mean    38.607732 -121.355982  
std      0.145433    0.138278  
min     38.241514 -121.551704  
25%     38.482717 -121.446127  
50%     38.626582 -121.376220  
75%     38.695589 -121.295778  
max     39.020808 -120.597599

In [35]:
house.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 985 entries, 0 to 984
Data columns (total 12 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   street     985 non-null    object 
 1   city       985 non-null    object 
 2   zip        985 non-null    int64  
 3   state      985 non-null    object 
 4   beds       985 non-null    int64  
 5   baths      985 non-null    int64  
 6   sq__ft     985 non-null    int64  
 7   type       985 non-null    object 
 8   sale_date  985 non-null    object 
 9   price      985 non-null    int64  
 10  latitude   985 non-null    float64
 11  longitude  985 non-null    float64
dtypes: float64(2), int64(5), object(5)
memory usage: 92.5+ KB


In [36]:
house.isnull().sum()

street       0
city         0
zip          0
state        0
beds         0
baths        0
sq__ft       0
type         0
sale_date    0
price        0
latitude     0
longitude    0
dtype: int64

In [37]:
#changing zip code to a string
house['zip'] = house['zip'].astype(str)

### 2. Predict Price

We are going to predict `price` from available information.

#### 2.1 What is the Target Variable? Why?

In [38]:
#We will use price as the target variable because we want to know which other factors from the data impact sales prices.
targetvariable = house.price

#### 2.2 List all possible variables which might be Independent/Predictor variable.

In [39]:
# ANSWER
# beds 
# bath
#sq__ft

#### 2.3 Find correlation between variables

Find correlation between variables. Which is the best predictor? Why? State your reason.

In [40]:
house.corr()

beds     baths    sq__ft     price  latitude  longitude
beds       1.000000  0.839650  0.684041  0.342024 -0.291307  -0.053993
baths      0.839650  1.000000  0.665690  0.416208 -0.235792   0.016582
sq__ft     0.684041  0.665690  1.000000  0.333897 -0.383274  -0.177742
price      0.342024  0.416208  0.333897  1.000000 -0.039573   0.284485
latitude  -0.291307 -0.235792 -0.383274 -0.039573  1.000000   0.387925
longitude -0.053993  0.016582 -0.177742  0.284485  0.387925   1.000000

In [41]:
#The best predictor value is sq__ft as it relates to both bath and beds

#### 2.4 Find Coefficient and Intercept using Linear Regression

Using LinearRegression of sklearn.linear_model package find Coefficient and Intercept.

Create an instance of LinearRegression.

Explore following methods:

- fit
- predict
- score

##### 2.4.1 Fit predictor and target variables using linear regression 

In [42]:
from sklearn.linear_model import LinearRegression

In [59]:
lin_reg = LinearRegression()

lin_reg.fit(X, Y)

#fit  = training your model, x variable to predict y value

LinearRegression()

In [62]:
lin_reg.coef_ #coefficient = Beta 1

array([[54.15863969]])

In [65]:
lin_reg.intercept_ #intercept = Beta 0

array([162930.161407])

In [67]:
lin_reg.score(X, Y) #R2 = the change in feature X explains 11% of the change in Y.

0.11148717682951437

In [43]:
# ANSWER

X = house['sq__ft'].values.reshape(-1,1)
Y = house['price'].values.reshape(-1,1)
print(X.shape, Y.shape)

(985, 1) (985, 1)


In [54]:
X[:5]

array([[ 836],
       [1167],
       [ 796],
       [ 852],
       [ 797]], dtype=int64)

In [55]:
Y[:5]

array([[59222],
       [68212],
       [68880],
       [69307],
       [81900]], dtype=int64)

In [44]:
reg = LinearRegression()
reg.fit(X, Y)

print(reg.coef_, reg.intercept_)

[[54.15863969]] [162930.161407]


##### 2.4.2 Find R Score

Find $R^2$ Using ```score``` method of Linear Regression.

In [69]:
r2 = reg.score(X, Y)
r2

0.11148717682951437

## 3. Splitting Data

#### 3.1 Create training and testing subsets

Hint: Using `train_test_split` Library.

```
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)
```

In [70]:
from sklearn.model_selection import train_test_split

In [71]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.33, random_state=42)

#### 3.2 Check Shape, Sample of Test Train Data

In [72]:
print(X_train.shape)
print(X_test.shape)
print(Y_train.shape)
print(Y_test.shape)

(659, 1)
(326, 1)
(659, 1)
(326, 1)


#### 3.3 Using Linear Regression Find The Score

1. Fit model using X_train, y_train
2. Find score using X_test, y_test

In [73]:
# Fit model using X_train, y_train
linreg = LinearRegression()
linreg.fit(X_train, Y_train)

print(linreg.coef_, linreg.intercept_)

[[47.43508406]] [166482.34144969]


In [74]:
# Find score using X_test, y_test
linreg.score(X_test, Y_test)

0.13602012247180006

### 4. Predict House Price

Let's assume we have information of following house:

- street:	1140 EDMONTON DR
- city:	SACRAMENTO
- zip:	95833
- state:	CA
- beds:	3
- baths:	2
- sq__ft:	1204
- type:	Residential

**Predict the price of this house using linear regression model.**

In [77]:
linreg.intercept_

array([166482.34144969])

In [78]:
linreg.coef_

array([[47.43508406]])

In [82]:
beta0 = linreg.intercept_
beta1 = linreg.coef_
x = 1204

Yprediction = beta0 + beta1 * x
print('Predicted house price: ', Yprediction[0])

Predicted house price:  [223594.18266381]


In [83]:
#Alternative code
# x = [[1204]]
# Ypred = linreg.predict(x)
# print('Predicted house price: ', Ypred[0])

#### Find the error

In [84]:
# Predict price from X_test

y_preds = linreg.predict(X_test)

y_preds[:10]

array([[209458.52761247],
       [279472.71169224],
       [259549.97638499],
       [248971.95263852],
       [238915.71481676],
       [166482.34144969],
       [166482.34144969],
       [256609.00117297],
       [166482.34144969],
       [166482.34144969]])

In [87]:
from sklearn.metrics import mean_squared_error

mean_squared_error(Y_test, y_preds, squared=True)

18951801967.76203



---



---



> > > > > > > > > © 2019 Institute of Data


---



---



